### PR TITLE
Handle Strong Customer Authentication transactions

### PR DESCRIPTION
**Pull request by gilhadas**
I'm trying to follow Apple requirement for:
Preparing for Strong Customer Authentication transactions in the European Economic Area

I didn't find a solution for that in framework.
please review my pr.
I couldn't find a way to get .purchasing status as apple suggested.
If you have better solution, you can ignore this pr, and let me know of other way.
Thanks
Gil

### CODE REVIEW

**Comment by jaceklapinski** [comment]
Same problem here

**Comment by gilhadas** [comment]
What is the problem?

**Comment by jaceklapinski** [comment]
Without your changes app not work correctly :) do they need to fix framework

**Comment by gilhadas** [comment]
I don’t get it. This workaround works for me, it is not helping for you?

**Comment by lrrrs** [comment]
From my understanding and my tests, `SwiftyStoreKit` already correctly handles interrupted purchases. 
When a purchase is interrupted, you should get a `.failed` transaction state and need to `finishTransaction`. 
This is already handled by `SwiftyStoreKit`. You'll receive a new transaction later that has the `.purchased` state.

See the guide `Begin Testing` here: https://developer.apple.com/documentation/storekit/in-app_purchase/testing_in-app_purchases_with_sandbox

The only thing you have to do in your code is to ignore the failed payment, if you would show an error in your app in that case.  `SwiftyStoreKit` translates the failed transaction into an `.unknown` error. You could simply ignore or log it…

Correct me if I'm wrong, but I think everything is fine with `SwiftyStoreKit`. When I try the PR, I have the issue, that the `.failed` transaction is never finished, because of the early return.

**Comment by NikKovIos** [comment]
Correctly you need to create new type of error and return it. Not just break the flow.

**Comment by sabiland** [comment]
I get unknownError case with interrupted purchase:

--->  case .unknown: self.updateInfoStatus("Unknown error")

`switch result {
                            case .success(_):
                                self.updateInfoStatus("Purchased")
                                self.makeTexturingPurchase()
                            case .error(let error):
                                switch error.code {
                                case .unknown: self.updateInfoStatus("Unknown error")
                                case .clientInvalid: self.updateInfoStatus("Not allowed to make the payment")
                                case .paymentCancelled: self.updateInfoStatus("Payment cancelled")
                                case .paymentInvalid: self.updateInfoStatus("The purchase identifier was invalid")
                                case .paymentNotAllowed: self.updateInfoStatus("The device is not allowed to make the payment")
                                case .storeProductNotAvailable: self.updateInfoStatus("The product is not available in the current storefront")
                                case .cloudServicePermissionDenied: self.updateInfoStatus("Access to cloud service information is not allowed")
                                case .cloudServiceNetworkConnectionFailed: self.updateInfoStatus("Could not connect to the network")
                                case .cloudServiceRevoked: self.updateInfoStatus("User has revoked permission to use this cloud service")
                                default: self.updateInfoStatus((error as NSError).localizedDescription)
                                }
                            }`

**Comment by gilhadas** [comment]
I'm closing this pr, It looks that apple change something in framework all is good now.

**Pull request closed without merging**
