### PR TITLE
Add Purchased Protocol

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
Add a shared protocol allowing Purchase, PurchaseDetails and ReceiptItem to be get a common treatment in simple cases

I noticed that I was getting different response types for purchases in

SwiftyStoreKit.completeTransactions (in .purchased and .restored cases)
SwiftyStoreKit.restorePurchases (for results.restoredPurchases)
SwiftyStoreKit.purchaseProducd (in .success case)

however - all I needed from each was the original purchase date and the productID.

this protocol allows me to route the three outputs through to a common purchase function.

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
I have mixed feelings about using var originalPurchaseDate:Date

I decided to keep the same method name as used elsewhere, but this requires a Date output rather than Date? 
This in turn leads to a theoretical possibility for fatalError in Purchase and PurchaseDetails

The alternative would be to use a different method like

var sharedOriginalPurchaseDate:Date? {get}

let me know what you think.

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ConfusedVorlon** [comment]
ping

**Comment by ConfusedVorlon** [comment]
Any thoughts?

**Comment by ConfusedVorlon** [comment]
still no comment here?

**Comment by Sam-Spencer** [comment]
Hi! This looks like a great PR. I'm going to take a deeper dive into your code soon and get back to you. In the meantime, would you mind writing some Unit Tests for this?

**Comment by ConfusedVorlon** [comment]
I have to admit that after being ignored for just over a year - I'm not feeling motivated to put in additional effort.

**Comment by Sam-Spencer** [comment]
I understand that sentiment. Unfortunately, the original maintainer on the project is no longer able to work on this and has asked for the community to step up in that vacuum. No one has come forward in over a year, so last week I offered to step up and start going through issues and pull requests. I don't think anybody _intended_ to ignore you or your contributions. They are very much valued. I invite you to join the Slack channel as well to help grow this project and the community around it.

**Comment by ConfusedVorlon** [comment]
Fair enough, that does put a different perspective on things.
Thanks for stepping up.

I won't be able to look at test cases this week, but should be able to next week.
Could you let me know your thoughts on the date issue?

**Comment by ConfusedVorlon** [comment]
> Could you let me know your thoughts on the date issue?

**Comment by Sam-Spencer** [comment]
Hmm I don't think a fatal error is necessarily bad. If an optional was returned, what might someone use in place of it? Could we maybe provide a specific date that could not possibly be an actual purchase date (say, Jan 1, 2000) instead?

**Comment by ConfusedVorlon** [comment]
thanks for approving.

just to close out the conversation; I don't like returning 'magic dates' - but on the other hand, if the fatal error actually can be triggered in production, then it would probably be better to change the protocol. I'm assuming it can't happen (and it hasn't happened to me in production), but let me know if you have better/different info.

**Comment by ConfusedVorlon** [comment]
I misunderstood; approved!=merged
have re-opened

**Comment by Sam-Spencer** [comment]
Thank you so much for your contribution! I plan on doing some testing in the coming days and getting everything from the develop branch into a new release on master.

**Comment by ConfusedVorlon** [comment]
belated thanks for taking on this project.
Congrats on clearing out all the pull requests!

**Pull request merged**
