### PR TITLE
Cancellable requests

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for SwiftyStoreKit.
In this pull request I added cancellable requests. Now developers can cancel such requests with `cancel()`.

### CODE REVIEW

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Sam-Spencer** [comment]
Looks fantastic! Merging now...

**Comment by Sam-Spencer** [comment]
Oops! Just realized -- any chance you could add a small bit of documentation on this to the README?

**Comment by RomanPodymov** [comment]
> Oops! Just realized -- any chance you could add a small bit of documentation on this to the README?

Hello @Sam-Spencer 
As far as I can see, you've already added it in https://github.com/bizz84/SwiftyStoreKit/commit/93a95d422cd72a29203988f5baf852cde4e87288.

**Pull request merged**
