### PR TITLE
Add support for downloading content hosted by Apple

### PR DESCRIPTION
**Pull request by bizz84**
Implementation for #128.

- [x] expose `[SKDownloads]` array on purchase success completion block
- [x] add `updatedDownloadsHandler` block to subscribe to updated downloads callbacks
- [x] add `start`/`pause`/`resume`/`cancel` calls to manage downloads status
- [x] update iOS demo app with usage example
- [x] fix existing unit tests
- [ ] add new unit tests
- [x] update README
- [x] update CHANGELOG

### CODE REVIEW

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bizz84** [comment]
I've been following this guide to create a In-App Purchase content package to test:

https://stackoverflow.com/questions/34724796/ios-archive-item-is-not-associated-with-any-known-itunes-connect-platform

My steps so far:
- Turn on content hosting for my IAP in iTunes connect
- Create an In-App Purchase content template in Xcode
- Ensure the IAPProductIdentifier matches my IAP
- Add an image to the target
- Archive the project
- Export as an installer package 
- Load it in Application Loader

When I try to deliver the selected content, I get this error:

screen shot 2018-01-29 at 21 40 47

So I can't test this.

Has anyone managed to upload hosted content to iTunes Connect?

**Comment by Vanyaslav** [comment]
Hi, I did manage to upload the hosted contents with  iTunes connect. When correctly done. It should look like this one. 
screen shot 2018-01-30 at 11 16 36

**Comment by Vanyaslav** [comment]
Actually I use this library with my own hacks to do the same job you are working on, but it is done simple and nasty way. So if you need an assistance to finish this, let me know. I'll be glad to have this thing sorted out as well proper way.

**Comment by aaru** [comment]
use iTMSTransporter command to upload your content.

**Pull request merged**
