### PR TITLE
Fixes for Swiftlint 0.22.0

### PR DESCRIPTION
**Pull request by tbaranes**
- [x] make the project compatible with swiftlint 0.22.0.
- [ ] Update swiftlint in `.travis.yml`

### CODE REVIEW

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please target PRs to <code>develop</code> branch</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bizz84** [comment]
@tbaranes thank you for this PR 👌

Could you update `.travis.yml` to run with the new version? This way the new swiftlint will be used on CI.

```
SWIFTLINT_PKG_URL="https://github.com/realm/SwiftLint/releases/download/0.22.0/SwiftLint.pkg"
```

**Comment by tbaranes** [comment]
Should be done 👍

**Comment by bizz84** [comment]
@tbaranes great! 🚀

**Pull request merged**
