### PR TITLE
Swift 4.1 / Xcode 9.3 Support

### PR DESCRIPTION
**Pull request by mattbarker016**
Removed warnings from `flatMap` depreciation. Changed to `compactMap`

### CODE REVIEW

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please target PRs to <code>develop</code> branch</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mattbarker016** [comment]
Changed branch, sorry about that! I'm guessing Travis isn't configured for Swift 4.1 for the other errors.

**Comment by bizz84** [comment]
Will this still compile with Xcode 8 though? 

Some users have not upgraded yet and I'm wary of introducing changes that may break the build on non-latest tools.

**Comment by mattbarker016** [comment]
Would adding ‘if #available(iOS 11.3, *)’ solve it? I can try when I’m near my computer.

**Comment by AndrewBennet** [comment]
Instead of `if #available(iOS 11.3, *)` I think you'll want something like:

```swift
#if swift(>=4.1)
let receiptItems = nonCancelledReceiptsInfo.compactMap { ReceiptItem(receiptInfo: $0) }
#else
let receiptItems = nonCancelledReceiptsInfo.flatMap { ReceiptItem(receiptInfo: $0) }
#endif
```

**Comment by mattbarker016** [comment]
Ugh, my bad

**Comment by AndrewBennet** [comment]
Hi @bizz84 - Can you explain what the Danger check is? Do tests need to be touched for every change?

**Comment by bizz84** [comment]
@mattbarker016 @AndrewBennet thanks for contributing! Don't worry about the Danger check. It's not very precise.

**Pull request merged**
