### PR TITLE
Added Swift 4.2 support.

### PR DESCRIPTION
**Pull request by spencerwhyte**
Trivial change to add Swift 4.2 support.

### CODE REVIEW

**Comment by bizz84** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests were not updated</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please target PRs to <code>develop</code> branch</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bizz84** [comment]
Tests failed due to a separate problem (see #404, #405).

Merging and fixing separately.

**Comment by bizz84** [comment]
@spencerwhyte thanks for contributing! Will create a new release soon.

**Comment by KingOlami** [comment]
hi please I have been unable to get this project to work kind view my issue and contribute to it please thanks. https://github.com/bizz84/SwiftyStoreKit/issues/412

**Pull request merged**
